predefined_responses = {
    "hello": "Hi there! How can I assist you?",
    "how are you": "I'm just a bot, but I'm doing great!",
    "bye": "Goodbye! Have a great day!",
    "who are you": "I'm your friendly chatbot, here to help!",
    "what's your name": "I'm Charles!",
    "what time is it": "I can tell you the time, but it might not be very accurate.",
    "what is the weather like today": "I do not have access to real-time weather information.",
    "tell me a joke": "Why don't scientists trust atoms anymore? Because they make up everything!",
    "tell me another joke": "What do you call a fish with no eyes? Fsh!",
    "what is your favorite color": "As a chatbot, I don't have preferences, but I think all colors are interesting!",
    "what is your favorite food": "I don't eat, but if I could, I'd probably like data. ",
    "do you like music": "I enjoy processing sound waves, but I don't have personal music taste.",
    "can you help me with math": "I can perform some math calculations.  What do you need help with?",
    "what is your purpose": "My purpose is to assist users with information and complete tasks as instructed.",
    "how do you work": "I am a large language model, trained by Google.",
    "are you intelligent": "I can process and generate text, but I don't have consciousness or true intelligence in the human sense.",
    "thank you": "You're welcome!",
    "thanks": "You're welcome!",
    "okay": "Okay!",
    "cool": "Cool!",
    "great": "Great!",
    "awesome": "Awesome!",
    "sounds good": "Sounds good!",
    "nice": "Nice!",
    "you are great": "Thank you!",
    "you are awesome": "Thank you!",
    "you are cool":"Thank you!",
    "good morning": "Good morning!",
    "good afternoon":"Good afternoon!",
    "good evening":"Good evening!",
    "good night":"Good night!",
    "how do you do":"I am doing well, thank you!",
    "what's up":"Not much, what's up with you?",
    "how's it going":"It's going well, how about you?",
    "nice to meet you":"Nice to meet you too!",
    "pleased to meet you":"Pleased to meet you too!",
    "it was nice talking to you":"It was nice talking to you too!",
    "see you later":"See you later!",
    "talk to you later":"Talk to you later!",
    "have a good one":"You too!",
    "have a nice day":"You too!",
    "take care":"You too!",
    "what are you doing":"I am currently helping you with your request.",
    "where are you from":"I am from Google.",
    "do you have any hobbies":"I don't have hobbies.",
    "are you a bot": "Yes, I am a chatbot.", #added
    "what can you do":"I can answer questions and have conversations with you." # added
}